server:
  port: 8765
spring:
  datasource:
    master:
      type: com.alibaba.druid.pool.DruidDataSource
      url: jdbc:mysql://localhost:3306/jpa?serverTimezone=UTC&characterEncoding=UTF-8
      username: root
      password: root
      driverClassName: com.mysql.cj.jdbc.Driver     # com.mysql.jdbc.Driver  # com.mysql.cj.jdbc.Driver
    slave:
      type: com.alibaba.druid.pool.DruidDataSource
      url: jdbc:mysql://localhost:3306/jpaa?serverTimezone=UTC&characterEncoding=UTF-8
      username: root
      password: root
      driverClassName: com.mysql.cj.jdbc.Driver  # com.mysql.cj.jdbc.Driver
  jpa:
    open-in-view: true
    database: mysql
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: true
        hbm2ddl:
          auto: update