server:
  port: 8765
spring:
  datasource:
    master:
      # type: com.alibaba.druid.pool.DruidDataSource
      url: jdbc:mysql://192.168.244.128:3307/jpa?serverTimezone=UTC&characterEncoding=UTF-8
      username: root
      password: 123456
      driverClassName: com.mysql.cj.jdbc.Driver     # com.mysql.jdbc.Driver  # com.mysql.cj.jdbc.Driver
    slave:
      # type: com.alibaba.druid.pool.DruidDataSource
      url: jdbc:mysql://192.168.244.128:3308/jpa?serverTimezone=UTC&characterEncoding=UTF-8
      username: root
      password: 123456
      driverClassName: com.mysql.cj.jdbc.Driver  # com.mysql.cj.jdbc.Driver
  jpa:
    open-in-view: true
    database: mysql
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: true
        hbm2ddl:
          auto: update